name: Oliviero
favicon: null
layout_spectrum: 0.7116590840741992
typography_spectrum: 0.1259684800170362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8893420503009111
  lightness: 0.7257116956170648
  saturation: 0.11038717092014849
  rhythmicContrast: 0.2140995841473341
purpose: []
